#!/usr/bin/env python3
"""Sync the Cowork estimator site with its source workbook.

Downloads the source xlsx (https://aka.ms/CustomerCoworkEstimator), extracts the
model assumptions from the Budget sheet, and regenerates estimator-data.json and
estimator-data.js when the values have changed.

Outputs (for GitHub Actions):
  - Writes step outputs `changed`, `recent`, and `summary` to $GITHUB_OUTPUT when set.
  - Exit code is always 0 unless an unrecoverable error occurs.
"""
from __future__ import annotations

import datetime as dt
import io
import json
import os
import sys
from email.utils import parsedate_to_datetime
from pathlib import Path

import requests
from openpyxl import load_workbook

SOURCE_URL = "https://aka.ms/CustomerCoworkEstimator"
ROOT = Path(__file__).resolve().parent.parent
DATA_JSON = ROOT / "estimator-data.json"
DATA_JS = ROOT / "estimator-data.js"

# Budget-sheet cell map. Roles are rows 23-26; per-prompt credits in D33/34/35.
ROLE_ROWS = [
    ("corp", "D23", "E23", "F23"),
    ("cust", "D24", "E24", "F24"),
    ("tech", "D25", "E25", "F25"),
    ("mgmt", "D26", "E26", "F26"),
]
# Role display names come from the Step 1 table (C12-C15), which match Step 2.
NAME_CELLS = {"corp": "C12", "cust": "C13", "tech": "C14", "mgmt": "C15"}
CPP_CELLS = {"light": "D33", "medium": "D34", "heavy": "D35"}


def _int(v) -> int:
    try:
        return int(round(float(v)))
    except (TypeError, ValueError):
        return 0


def fetch() -> tuple[bytes, "dt.datetime | None"]:
    r = requests.get(SOURCE_URL, timeout=60, allow_redirects=True)
    r.raise_for_status()
    last_mod = None
    lm = r.headers.get("Last-Modified")
    if lm:
        try:
            last_mod = parsedate_to_datetime(lm)
        except (TypeError, ValueError):
            last_mod = None
    return r.content, last_mod


def extract(content: bytes) -> dict:
    wb = load_workbook(io.BytesIO(content), data_only=True)
    ws = wb["Budget"]
    roles = []
    for rid, lc, mc, hc in ROLE_ROWS:
        roles.append(
            {
                "id": rid,
                "name": str(ws[NAME_CELLS[rid]].value).strip(),
                "users": 0,
                "light": _int(ws[lc].value),
                "medium": _int(ws[mc].value),
                "heavy": _int(ws[hc].value),
            }
        )
    cpp = {k: _int(ws[c].value) for k, c in CPP_CELLS.items()}
    return {"roles": roles, "creditsPerPrompt": cpp}


def load_existing() -> "dict | None":
    if DATA_JSON.exists():
        try:
            return json.loads(DATA_JSON.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            return None
    return None


def core(d: "dict | None") -> "dict | None":
    """Comparable subset (ignore timestamps)."""
    if not d:
        return None
    return {"roles": d.get("roles"), "creditsPerPrompt": d.get("creditsPerPrompt")}


def write_outputs(model: dict, last_mod: "dt.datetime | None") -> None:
    now = dt.datetime.now(dt.timezone.utc)
    payload = {
        "source": SOURCE_URL,
        "lastModified": last_mod.astimezone(dt.timezone.utc).isoformat() if last_mod else None,
        "lastSynced": now.isoformat(),
        "roles": model["roles"],
        "creditsPerPrompt": model["creditsPerPrompt"],
    }
    DATA_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    js = (
        "/* Auto-generated by scripts/sync_estimator.py. Do not edit by hand. */\n"
        "window.ESTIMATOR_DATA = " + json.dumps(payload, indent=2) + ";\n"
    )
    DATA_JS.write_text(js, encoding="utf-8")


def set_action_output(**kw) -> None:
    path = os.environ.get("GITHUB_OUTPUT")
    if not path:
        return
    with open(path, "a", encoding="utf-8") as fh:
        for k, v in kw.items():
            fh.write(f"{k}={v}\n")


def main() -> int:
    try:
        content, last_mod = fetch()
        model = extract(content)
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: sync failed: {exc}", file=sys.stderr)
        set_action_output(changed="false", recent="false", summary=f"Sync failed: {exc}")
        return 1

    existing = load_existing()
    changed = core(existing) != core(model)

    now = dt.datetime.now(dt.timezone.utc)
    recent = bool(last_mod and (now - last_mod) <= dt.timedelta(days=7))
    lm_str = last_mod.astimezone(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC") if last_mod else "unknown"

    if changed:
        write_outputs(model, last_mod)
        diffs = []
        old = core(existing) or {}
        if old.get("creditsPerPrompt") != model["creditsPerPrompt"]:
            diffs.append(f"credits/prompt {old.get('creditsPerPrompt')} -> {model['creditsPerPrompt']}")
        if old.get("roles") != model["roles"]:
            diffs.append("role prompt mix changed")
        summary = f"Updated. Source last modified {lm_str}. " + ("; ".join(diffs) if diffs else "values changed")
    else:
        if existing is None:
            write_outputs(model, last_mod)
            summary = f"Baseline created. Source last modified {lm_str}."
        else:
            summary = f"No change. Source last modified {lm_str}."

    print(summary)
    set_action_output(
        changed="true" if changed else "false",
        recent="true" if recent else "false",
        summary=summary,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
